### ISSUE TITLE
WTF.sql does not always work

### ISSUE THREAD

**Issue by Nedomas** [remigijusj/wtf-tools#2]
It seems that `WTF.sql` only works for some sql queries and it seems to not output anything on more complex ones.

Example of a bit more complex query.

``` sql
SELECT "missions".* FROM "missions" WHERE (ARRAY[432,433,434,435,436,437,438] && factual_categories) AND "missions"."id" IN (2, 1)
```

**Comment by remigijusj** [comment]
Since the hook place in Rails 4.2 is exactly the same as in 4.1, your issue probably has something to do with Postgres SQL.

I have pushed an update (v1.0.1) which lets you specify regexp or proc instead of simple SQL string. Try to do `WTF.sql /SELECT .../` and let me know if that works.

**Comment by Nedomas** [comment]
I'll report that in a few hours

**Comment by Nedomas** [comment]
*''Few hours later''* - It worked!
